"""
Exoplanet Hunting — Prediction API

Run locally with:
    uvicorn app.main:app --reload

Then visit http://127.0.0.1:8000/docs for interactive API docs (auto-generated by FastAPI).
"""

import numpy as np
import joblib
from fastapi import FastAPI, HTTPException

from app.preprocessing import extract_features
from app.schemas import FluxInput, PredictionOutput

app = FastAPI(
    title="Exoplanet Hunting API",
    description="Predicts whether a star hosts a transiting exoplanet, based on its flux time series.",
    version="0.1.0",
)

MODEL_PATH = "models/exoplanet_model.joblib"

# Load once at startup, not per-request — loading a model from disk on
# every request would be slow and pointless since it never changes.
try:
    bundle = joblib.load(MODEL_PATH)
    model = bundle["model"]
    feature_cols = bundle["feature_cols"]
except FileNotFoundError:
    model = None
    feature_cols = None

@app.get("/health")
def health_check():
    """Simple endpoint to confirm the service is up and the model loaded correctly."""
    return {
        "status": "ok" if model is not None else "model_not_loaded",
    }

@app.post("/predict", response_model=PredictionOutput)
def predict(input_data: FluxInput):
    if model is None:
        raise HTTPException(status_code=503, detail="Model not loaded on server")

    flux_array = np.array(input_data.flux).reshape(1, -1)  # shape (1, 3197)

    features_df = extract_features(flux_array)
    features_df = features_df[feature_cols]  # enforce exact training-time column order

    probability = model.predict_proba(features_df.values)[0, 1]
    prediction = "planet" if probability >= 0.5 else "no_planet"

    return PredictionOutput(prediction=prediction, probability=float(probability))