"""
Exoplanet Hunting — Prediction API

Run locally with:
    uvicorn app.main:app --reload

Then visit http://127.0.0.1:8000/docs for interactive API docs (auto-generated by FastAPI).
"""

import logging
import time
from datetime import datetime, timezone

import numpy as np
import joblib
from fastapi import FastAPI, HTTPException, Request

from app.preprocessing import extract_features
from app.schemas import FluxInput, PredictionOutput

# --- Logging setup ---
# Logs to stdout, which Render (and most hosting platforms) automatically
# captures and shows in their dashboard's log viewer — no extra config
# needed to see these in production.
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
)
logger = logging.getLogger("exoplanet_api")

app = FastAPI(
    title="Exoplanet Hunting API",
    description="Predicts whether a star hosts a transiting exoplanet, based on its flux time series.",
    version="0.1.0",
)

MODEL_PATH = "models/exoplanet_model.joblib"

# Load once at startup, not per-request — loading a model from disk on
# every request would be slow and pointless since it never changes.
try:
    bundle = joblib.load(MODEL_PATH)
    model = bundle["model"]
    feature_cols = bundle["feature_cols"]
    logger.info(f"Model loaded successfully from {MODEL_PATH}")
except FileNotFoundError:
    model = None
    feature_cols = None
    logger.error(f"Model file not found at {MODEL_PATH} — service will report unhealthy")

# --- In-memory stats tracking ---
# NOTE: this is intentionally simple — resets on every restart and won't
# stay consistent if the service ever runs multiple worker processes.
# That's a real limitation, not an oversight: proper production monitoring
# would use something external (e.g. Prometheus, or a logging service that
# aggregates across instances) rather than in-process state. This is a
# "good enough to see it's alive and roughly how it's behaving" solution,
# appropriate for this project's scale.
stats = {
    "total_requests": 0,
    "total_predictions": 0,
    "planet_predictions": 0,
    "no_planet_predictions": 0,
    "total_latency_ms": 0.0,
    "started_at": datetime.now(timezone.utc).isoformat(),
}

@app.middleware("http")
async def log_requests(request: Request, call_next):
    start_time = time.perf_counter()
    response = await call_next(request)
    duration_ms = (time.perf_counter() - start_time) * 1000
 
    stats["total_requests"] += 1
 
    logger.info(
        f"{request.method} {request.url.path} -> {response.status_code} "
        f"({duration_ms:.1f}ms)"
    )
    return response

@app.get("/")
def root():
    return {"message": "Exoplanet Hunting API — see /docs for interactive usage"}

@app.get("/health")
def health_check():
    """Simple endpoint to confirm the service is up and the model loaded correctly."""
    return {
        "status": "ok" if model is not None else "model_not_loaded",
    }

@app.get("/stats")
def get_stats():
    """Lightweight in-process monitoring - request/prediction counts and
    average latency since the service last started. See NOTE above the
    `stats` dict for why this is process-local, not a substitute for real
    production monitoring at larger scale."""
    avg_latency = (
        stats["total_latency_ms"] / stats["total_predictions"]
        if stats["total_predictions"] > 0
        else 0.0
    )
    return {
        **stats,
        "avg_prediction_latency_ms": round(avg_latency, 2),
    }

@app.post("/predict", response_model=PredictionOutput)
def predict(input_data: FluxInput):
    if model is None:
        logger.error("Prediction requested but model is not loaded")
        raise HTTPException(status_code=503, detail="Model not loaded on server")

    start_time = time.perf_counter()

    flux_array = np.array(input_data.flux).reshape(1, -1)  # shape (1, 3197)

    features_df = extract_features(flux_array)
    features_df = features_df[feature_cols]  # enforce exact training-time column order

    probability = model.predict_proba(features_df.values)[0, 1]
    prediction = "planet" if probability >= 0.5 else "no_planet"

    latency_ms = (time.perf_counter() - start_time) * 1000

    # Update stats
    stats["total_predictions"] += 1
    stats["total_latency_ms"] += latency_ms
    if prediction == "planet":
        stats["planet_predictions"] += 1
    else:
        stats["no_planet_predictions"] += 1
 
    logger.info(
        f"Prediction: {prediction} (probability={probability:.4f}, latency={latency_ms:.1f}ms)"
    )

    return PredictionOutput(prediction=prediction, probability=float(probability))